_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
epochs:
    value: 3
lora_rank:
    value: 8
lr:
    value: 1e-05
