_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 98
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
batch_size:
    value: 1
effective_batch_size:
    value: 8
epochs:
    value: 1
gpu:
    value: RTX 3060
learning_rate:
    value: 1e-05
lora_rank:
    value: 4
model:
    value: google/paligemma-3b-mix-224
